# Generated by Django 5.2.8 on 2025-11-15 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from typing import ClassVar


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("login", "User Login"), ("logout", "User Logout"), ("create_user", "Create User Account"), ("update_user", "Update User Account"), ("deactivate_user", "Deactivate User"), ("reactivate_user", "Reactivate User"), ("reset_password", "Reset Password"), ("case_create", "Case Created"), ("case_update", "Case Updated"), ("case_status_change", "Case Status Changed"), ("case_receipt", "Case Physically Received"), ("case_approval", "Case Approved"), ("case_rejection", "Case Rejected"), ("case_release", "Case Released")], max_length=50)),
                ("target_object", models.CharField(blank=True, help_text="e.g., Case ID: CEB-2025...", max_length=255)),
                ("details", models.JSONField(blank=True, default=dict, help_text="Extra context in JSON")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_logs", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("target_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="target_audit_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["action"], name="core_auditl_action_d9fb24_idx"), models.Index(fields=["created_at"], name="core_auditl_created_dc23ea_idx"), models.Index(fields=["actor"], name="core_auditl_actor_i_870709_idx")],
            },
        ),
    ]
