# pyright: reportArgumentType=false
# Generated by Django 5.2.8 on 2025-11-15 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from typing import ClassVar


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0002_auditlog"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activation_token", models.CharField(blank=True, max_length=40, null=True)),
                ("activation_expiry", models.DateTimeField(blank=True, null=True)),
                ("must_change_password", models.BooleanField(default=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
