# Generated by Django 5.2.8 on 2025-11-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
