# Generated by Django 5.2.8 on 2025-11-16 21:10

from django.db import migrations
from typing import ClassVar


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0004_case"),
    ]

    operations: ClassVar[list] = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
