# Generated by Django 5.2.8 on 2025-12-16 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_case_received_by_case_return_reason_case_returned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create_user', 'Create User Account'), ('update_user', 'Update User Account'), ('deactivate_user', 'Deactivate User'), ('reactivate_user', 'Reactivate User'), ('reset_password', 'Reset Password'), ('case_create', 'Case Created'), ('case_update', 'Case Updated'), ('case_status_change', 'Case Status Changed'), ('case_receipt', 'Case Physically Received'), ('case_assignment', 'Case Assigned'), ('case_approval', 'Case Approved'), ('case_rejection', 'Case Rejected'), ('case_release', 'Case Released')], max_length=50),
        ),
    ]
