# pyright: reportArgumentType=false
# Generated by Django 5.2.8 on 2025-12-16 15:36

from django.db import migrations, models
from typing import ClassVar


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0007_case_assigned_at_case_assigned_to_and_more"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="customuser",
            name="designation",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
