# Generated by Django 5.2.8 on 2025-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_nonce',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='temp_password_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('login_failed', 'User Login Failed'), ('logout', 'User Logout'), ('create_user', 'Create User Account'), ('update_user', 'Update User Account'), ('deactivate_user', 'Deactivate User'), ('reactivate_user', 'Reactivate User'), ('reset_password', 'Reset Password'), ('activation_email_sent', 'Activation Email Sent'), ('activate_account', 'Account Activated'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_complete', 'Password Reset Completed'), ('case_create', 'Case Created'), ('case_update', 'Case Updated'), ('case_status_change', 'Case Status Changed'), ('case_receipt', 'Case Physically Received'), ('case_assignment', 'Case Assigned'), ('case_approval', 'Case Approved'), ('case_rejection', 'Case Rejected'), ('case_release', 'Case Released')], max_length=50),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='core_passwo_email_465400_idx'), models.Index(fields=['requested_at'], name='core_passwo_request_3b51d6_idx')],
            },
        ),
    ]
