# Generated by Django 5.2.8 on 2025-12-16 18:15

from django.db import migrations, models
from typing import ClassVar


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0010_casedocument"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="customuser",
            name="lgu_municipality",
            field=models.CharField(blank=True, choices=[("Alcantara", "Alcantara"), ("Alcoy", "Alcoy"), ("Alegria", "Alegria"), ("Aloguinsan", "Aloguinsan"), ("Argao", "Argao"), ("Asturias", "Asturias"), ("Badian", "Badian"), ("Balamban", "Balamban"), ("Bantayan", "Bantayan"), ("Barili", "Barili"), ("Boljoon", "Boljoon"), ("Borbon", "Borbon"), ("Carmen", "Carmen"), ("Catmon", "Catmon"), ("Compostela", "Compostela"), ("Consolacion", "Consolacion"), ("Cordova", "Cordova"), ("Daanbantayan", "Daanbantayan"), ("Dalaguete", "Dalaguete"), ("Dumanjug", "Dumanjug"), ("Ginatilan", "Ginatilan"), ("Liloan", "Liloan"), ("Madridejos", "Madridejos"), ("Malabuyoc", "Malabuyoc"), ("Medellin", "Medellin"), ("Minglanilla", "Minglanilla"), ("Moalboal", "Moalboal"), ("Oslob", "Oslob"), ("Pilar (Camotes)", "Pilar (Camotes)"), ("Pinamungajan", "Pinamungajan"), ("Poro (Camotes)", "Poro (Camotes)"), ("Ronda", "Ronda"), ("Samboan", "Samboan"), ("San Fernando", "San Fernando"), ("San Francisco (Camotes)", "San Francisco (Camotes)"), ("San Remigio", "San Remigio"), ("Santa Fe (Bantayan Island)", "Santa Fe (Bantayan Island)"), ("Santander", "Santander"), ("Sibonga", "Sibonga"), ("Sogod", "Sogod"), ("Tabogon", "Tabogon"), ("Tabuelan", "Tabuelan"), ("Tuburan", "Tuburan"), ("Tudela (Camotes)", "Tudela (Camotes)")], max_length=64),
        ),
    ]
