# Generated by Django 5.2.8 on 2025-12-17 00:37

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_customuser_lgu_municipality'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
    ]
