# Generated by Django 5.2.8 on 2025-12-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lgu_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
