# Generated by Django 5.2.8 on 2025-12-17 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_case_lgu_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('login_failed', 'User Login Failed'), ('logout', 'User Logout'), ('create_user', 'Create User Account'), ('update_user', 'Update User Account'), ('deactivate_user', 'Deactivate User'), ('reactivate_user', 'Reactivate User'), ('reset_password', 'Reset Password'), ('activation_email_sent', 'Activation Email Sent'), ('activate_account', 'Account Activated'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_complete', 'Password Reset Completed'), ('case_create', 'Case Created'), ('case_update', 'Case Updated'), ('case_remark', 'Case Remark Added'), ('case_status_change', 'Case Status Changed'), ('case_receipt', 'Case Physically Received'), ('case_assignment', 'Case Assigned'), ('case_approval', 'Case Approved'), ('case_rejection', 'Case Rejected'), ('case_release', 'Case Released')], max_length=50),
        ),
        migrations.CreateModel(
            name='CaseRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='core.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
