# Generated by Django 5.2.6 on 2026-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_faqitem_supportfeedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('login_failed', 'User Login Failed'), ('logout', 'User Logout'), ('create_user', 'Create User Account'), ('update_user', 'Update User Account'), ('deactivate_user', 'Deactivate User'), ('reactivate_user', 'Reactivate User'), ('reset_password', 'Reset Password'), ('activation_email_sent', 'Activation Email Sent'), ('activate_account', 'Account Activated'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_complete', 'Password Reset Completed'), ('case_create', 'Case Created'), ('case_update', 'Case Updated'), ('case_remark', 'Case Remark Added'), ('case_status_change', 'Case Status Changed'), ('case_receipt', 'Case Physically Received'), ('case_assignment', 'Case Assigned'), ('case_approval', 'Case Approved'), ('case_rejection', 'Case Rejected'), ('case_release', 'Case Released'), ('support_feedback', 'Support Feedback Submitted')], max_length=50),
        ),
    ]
