# Generated by Django 5.2.8 on 2026-01-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('land_first_time', 'Land declared for the first-time'), ('building_improvements', 'Building and other improvements / Machineries'), ('subdivision_consolidation', 'Subdivision or Consolidation'), ('reassessment_reclassification', 'Re-assessment / Re-classification'), ('area_increase_decrease', 'Increase / Decrease of Area'), ('transfer_ownership_tax_decl', 'Transfer of Ownership of Tax Declaration')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='case',
            name='client_first_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='client_last_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='client_middle_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='client_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='client_suffix',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='numbering_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_object',
            field=models.CharField(blank=True, help_text='e.g., Case: PAS26010001', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('lgu_admin', 'LGU Admin'), ('capitol_receiving', 'Capitol Receiver'), ('capitol_examiner', 'Capitol Examiner'), ('capitol_approver', 'Capitol Approver'), ('capitol_numberer', 'Capitol Numberer'), ('capitol_releaser', 'Capitol Releaser')], max_length=50),
        ),
    ]
