# Generated by Django 5.2.6 on 2025-11-12 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=64, unique=True)),
                ('submitted_by_lgu', models.CharField(max_length=128)),
                ('client_name', models.CharField(max_length=256)),
                ('client_contact', models.CharField(blank=True, max_length=128, null=True)),
                ('document_type', models.CharField(choices=[('land_title', 'Land Title'), ('tax_declaration', 'Tax Declaration')], max_length=64)),
                ('checklist', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('released', 'Released'), ('returned', 'Returned for Correction'), ('withdrawn', 'Withdrawn')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
